AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
